## The makeCacheMatrix function creates an object to store the given matrix and the calculated inverse. It acts like a cache.
## 
## The cacheSolve function makes use of the cached data in the object generated by the makecacheMatrix function to
## to avoid redundant calculations.



## makeCacheMatrix function creates an object with 
## the list of functions available to get and set the matrix 
## and store( by calling setinverse function) and retrieve(by calling getinverse function)
## the calculated inverse of the matrix.

makeCacheMatrix <- function(x = matrix()) {  # x is the intial matrix

	  # i is computed inverse and is set to NULL everytime 
	  # the function is called	

        i <- NULL	
	
	#sets the object with a new matrix and resets the inverse to NULL			

        set <- function(y) {
                x <<- y
                i <<- NULL
        }
	  
        get <- function() x    # gets the original matrix

	  # stores the inverse calculated for the new matrix

        setinverse <- function(inverse) i <<- inverse 

	  # returns the cached calculated inverse from the second time
        getinverse <- function() i

	  # the object created after the execution of this function has 
	  # the functions on the list are available for access.

        list(set = set, 
		get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}


## cacheSolve function checks if the inverse for the given matrix
## has already been calculated. It retrieves the data if exists else
## calculates and stores it.

cacheSolve <- function(x, ...) {   # x is the object generated by makeCacheMatrix 
	 # checks and retrieves the value from the object 
	 # if the inverse has already been calculated and stored 
	 # for the given matrix else returns NULL
         i <- x$getinverse()
	 # if not NULL then the cached value is returned with message stating that
         if(!is.null(i)) {
                message("getting cached data")
                return(i)
         }
	 # if the value is NULL or has not been calculated before new value is 
	 # calculated, stored for later use and the value is returned.
        data <- x$get()
        i <- solve(data, ...)
        x$setinverse(i)
        i
}
